basePath: /api/v1
definitions:
  dto.CreateWorkspaceRequestDTO:
    properties:
      description:
        type: string
      name:
        type: string
      type:
        allOf:
        - $ref: '#/definitions/model.WorkspaceType'
        enum:
        - personal
        - family
        - team
    required:
    - name
    - type
    type: object
  dto.LoginRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponseDTO:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.LogoutRequestDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RefreshRequestDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RefreshResponseDTO:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.RegisterRequestDTO:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  helper.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  model.WorkspaceType:
    enum:
    - personal
    - family
    - team
    type: string
    x-enum-varnames:
    - PersonalWorkspace
    - FamilyWorkspace
    - TeamWorkspace
info:
  contact:
    email: sauravkarn541@gmail.com
    name: API Support
    url: http://github.com/saurav-lal-karn/moniq/issues
  description: This is the API documentation for the Moniq Backend.
  termsOfService: http://example.com/terms/
  title: Moniq Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.LoginResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Login user
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout the user
      parameters:
      - description: Logout Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LogoutRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - Auth
  /auth/logout-all:
    get:
      consumes:
      - application/json
      description: Logout the user from all devices
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Logout from all devices
      tags:
      - Auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Details of logged in user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.LoginResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Me
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh token for user
      parameters:
      - description: Refresh token Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RefreshResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Refresh token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Register user
      tags:
      - Auth
  /workspace/create:
    post:
      consumes:
      - application/json
      description: Create workspace
      parameters:
      - description: CreateWorkspace Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateWorkspaceRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Create workspace
      tags:
      - Workspace
  /workspace/details/{id}:
    get:
      consumes:
      - application/json
      description: Get Workspace details
      parameters:
      - description: Workspace Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Get workspace details
      tags:
      - Workspace
  /workspace/list:
    get:
      consumes:
      - application/json
      description: List of user's workspaces
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: List My Workspace
      tags:
      - Workspace
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
